ALTER TABLE ARG.CITY_L
 DROP PRIMARY KEY CASCADE;

DROP TABLE ARG.CITY_L CASCADE CONSTRAINTS;

CREATE TABLE ARG.CITY_L
(
  CITY_ID  INTEGER,
  CITY     VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE ARG.COUNTRY
 DROP PRIMARY KEY CASCADE;

DROP TABLE ARG.COUNTRY CASCADE CONSTRAINTS;

CREATE TABLE ARG.COUNTRY
(
  COUNTRY_ID  INTEGER,
  COUNTRY     VARCHAR2(100 BYTE),
  CITY_ID     INTEGER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE ARG.PRIZE
 DROP PRIMARY KEY CASCADE;

DROP TABLE ARG.PRIZE CASCADE CONSTRAINTS;

CREATE TABLE ARG.PRIZE
(
  PRIZE_ID   INTEGER,
  PRIZENAME  VARCHAR2(100 BYTE),
  YEAR       INTEGER,
  CATEGORY   VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


ALTER TABLE ARG.PRIZE_DETAIL
 DROP PRIMARY KEY CASCADE;

DROP TABLE ARG.PRIZE_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE ARG.PRIZE_DETAIL
(
  PRIZE_ID     INTEGER,
  MOTIVATION   VARCHAR2(100 BYTE),
  LAUREATE_ID  INTEGER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX ARG.CITY_L_PK ON ARG.CITY_L
(CITY_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX ARG.COUNTRY_PK ON ARG.COUNTRY
(COUNTRY_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX ARG.PRIZE_DETAIL_PK ON ARG.PRIZE_DETAIL
(LAUREATE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX ARG.PRIZE_PK ON ARG.PRIZE
(PRIZE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE ARG.LAUREATES
 DROP PRIMARY KEY CASCADE;

DROP TABLE ARG.LAUREATES CASCADE CONSTRAINTS;

CREATE TABLE ARG.LAUREATES
(
  LAUREATE_ID     INTEGER,
  NAME            VARCHAR2(100 BYTE),
  COUNTRY_ID      INTEGER,
  BIRTHDAY        DATE,
  ROLE_AFFILIATE  VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX ARG.LAUREATES_PK ON ARG.LAUREATES
(LAUREATE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE ARG.CITY_L ADD (
  CONSTRAINT CITY_L_PK
  PRIMARY KEY
  (CITY_ID)
  USING INDEX ARG.CITY_L_PK
  ENABLE VALIDATE);

ALTER TABLE ARG.COUNTRY ADD (
  CONSTRAINT COUNTRY_PK
  PRIMARY KEY
  (COUNTRY_ID)
  USING INDEX ARG.COUNTRY_PK
  ENABLE VALIDATE);

ALTER TABLE ARG.PRIZE ADD (
  CONSTRAINT PRIZE_PK
  PRIMARY KEY
  (PRIZE_ID)
  USING INDEX ARG.PRIZE_PK
  ENABLE VALIDATE);

ALTER TABLE ARG.PRIZE_DETAIL ADD (
  CONSTRAINT PRIZE_DETAIL_PK
  PRIMARY KEY
  (LAUREATE_ID)
  USING INDEX ARG.PRIZE_DETAIL_PK
  ENABLE VALIDATE);

ALTER TABLE ARG.LAUREATES ADD (
  CONSTRAINT LAUREATES_PK
  PRIMARY KEY
  (LAUREATE_ID)
  USING INDEX ARG.LAUREATES_PK
  ENABLE VALIDATE);

ALTER TABLE ARG.COUNTRY ADD (
  CONSTRAINT COUNTRY_R01 
  FOREIGN KEY (CITY_ID) 
  REFERENCES ARG.
  ENABLE VALIDATE);

ALTER TABLE ARG.PRIZE_DETAIL ADD (
  CONSTRAINT PRIZE_DETAIL_R01 
  FOREIGN KEY (PRIZE_ID) 
  REFERENCES ARG.
  ENABLE VALIDATE);

ALTER TABLE ARG.LAUREATES ADD (
  CONSTRAINT LAUREATES_R01 
  FOREIGN KEY (COUNTRY_ID) 
  REFERENCES ARG.
  ENABLE VALIDATE,
  CONSTRAINT LAUREATES_R02 
  FOREIGN KEY (LAUREATE_ID) 
  REFERENCES ARG.
  ENABLE VALIDATE);
